name: messenger_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  build_runner: ^2.9.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  encrypt: ^5.0.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_chat_ui: ^2.9.1
  flutter_local_notifications: ^19.4.2
  flutter_secure_storage: ^9.2.4
  get_it: ^8.2.0
  go_router: ^16.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  injectable: ^2.5.2
  intl: ^0.20.2
  json_serializable: ^6.11.1
  jwt_decoder: ^2.0.1
  liquid_glass_renderer: ^0.1.1-dev.20
  shared_preferences: ^2.5.3
  web_socket_channel: ^3.0.3
  logger: ^2.6.2
  stomp_dart_client: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.9.0
  injectable_generator: ^2.9.0

flutter:
  uses-material-design: true
